# Track, Module, Pattern, Problem, Platform, Difficulty, Recognition Trigger, Core Insight

T1 = "T1: Arrays, Strings & Two Pointers"
T2 = "T2: Stacks, Binary Search, Linked Lists & Intervals"
T3 = "T3: Trees & Tries"
T4 = "T4: Heaps, Backtracking & Greedy"
T5 = "T5: Graphs"
T6 = "T6: Dynamic Programming"
T7 = "T7: CP Toolkit - Bits, Math, Strings & Advanced DS"

M1 = "M1: Arrays & Hashing Foundations"
M2 = "M2: Two Pointers & Sliding Window"
M3 = "M3: Stack & Monotonic Structures"
M4 = "M4: Binary Search - All Forms"
M5 = "M5: Linked List"
M6 = "M6: Intervals"
M7 = "M7: Trees - Traversal & Construction"
M8 = "M8: Trees - Advanced DP & Path Problems"
M9 = "M9: Tries"
M10 = "M10: Heaps & Priority Queues"
M11 = "M11: Backtracking"
M12 = "M12: Greedy"
M13 = "M13: Graphs - BFS/DFS Foundations"
M14 = "M14: Graphs - Union Find & Topological Sort"
M15 = "M15: Graphs - Advanced (MST, SCC, Bridges, Shortest Path)"
M16 = "M16: DP - 1D & Knapsack"
M17 = "M17: DP - 2D, Grid & String"
M18 = "M18: DP - Advanced (Bitmask, Tree DP, Interval DP, DAG DP)"
M19 = "M19: Bit Manipulation"
M20 = "M20: String Algorithms"
M21 = "M21: Number Theory & Math"
M22 = "M22: Advanced Data Structures (Segment Tree, BIT, Sqrt Decomposition)"

DATA = []

DATA += [
(T1,M1,"Hashmap complement lookup","Two Sum","LeetCode","Easy","Find pair summing to target","Hashmap stores complement while scanning"),
(T1,M1,"Hashset membership","Contains Duplicate","LeetCode","Easy","Any value repeats","Hashset membership check"),
(T1,M1,"Frequency comparison","Valid Anagram","LeetCode","Easy","Same letters, different order","Frequency count comparison"),
(T1,M1,"Hash-key normalization","Group Anagrams","LeetCode","Medium","Cluster words by letter composition","Sorted string or count-tuple as hashmap key"),
(T1,M1,"Frequency + bucket sort","Top K Frequent Elements","LeetCode","Medium","K most common items","Frequency map, then bucket sort by count"),
(T1,M1,"Length-prefix encoding","Encode and Decode Strings","LeetCode","Medium","Pack/unpack list of strings safely","Length-prefix each string before joining"),
(T1,M1,"Hashset run detection","Longest Consecutive Sequence","LeetCode","Medium","O(n) run length in unsorted array","Hashset, only start counting from run-starts"),
(T1,M1,"Prefix x suffix pass","Product of Array Except Self","LeetCode","Medium","Value at i needs all others","Left-pass times right-pass, no division"),
(T1,M1,"Constraint hashsets","Valid Sudoku","LeetCode","Medium","Check row/col/box constraints","Three hashsets keyed by row, col, box-id"),
(T1,M1,"Prefix sum + hashmap","Subarray Sum Equals K","LeetCode","Medium","Count subarrays summing to K","Running sum + hashmap of prefix-sum counts"),
(T1,M1,"Boyer-Moore voting","Majority Element","LeetCode","Easy","Element appearing more than n/2 times","Candidate + counter cancels out minority votes"),
(T1,M1,"Three-pointer partition","Sort Colors (Dutch Flag)","LeetCode","Medium","3-way partition in one pass","Three pointers: low, mid, high"),
(T1,M1,"Matrix marker trick","Set Matrix Zeroes","LeetCode","Medium","Mark rows/cols without extra space","Use first row/col of matrix as markers"),
(T1,M1,"Transpose + reverse","Rotate Image","LeetCode","Medium","Rotate matrix in place","Transpose the matrix, then reverse each row"),
(T1,M1,"Boundary shrink","Spiral Matrix","LeetCode","Medium","Traverse in spiral order","Shrink four boundaries (top/bottom/left/right) each lap"),
(T1,M2,"Two pointer squeeze","Valid Palindrome","LeetCode","Easy","Check symmetry ignoring non-alnum chars","Left/right pointer squeeze toward center"),
(T1,M2,"Sorted two pointer","Two Sum II (sorted array)","LeetCode","Medium","Pair sum in a sorted array","Pointers move inward based on sum vs target"),
(T1,M2,"Sort + fix + two pointer","3Sum","LeetCode","Medium","Triplets summing to zero","Sort array, fix one value, two-pointer the rest"),
(T1,M2,"Greedy pointer move","Container With Most Water","LeetCode","Medium","Maximize area between two lines","Move the shorter pointer inward each step"),
(T1,M2,"Two pointer + running max","Trapping Rain Water","LeetCode","Hard","Water trapped between bars","Two pointer with running max height on each side"),
(T1,M2,"Running minimum","Best Time to Buy and Sell Stock","LeetCode","Easy","Max profit, single transaction","Track minimum price seen so far while scanning"),
(T1,M2,"Variable window + set","Longest Substring Without Repeating Characters","LeetCode","Medium","Longest window with unique chars","Expand right, shrink left the moment a repeat appears"),
(T1,M2,"Window validity formula","Longest Repeating Character Replacement","LeetCode","Medium","Window allowing at most K replacements","Window valid if (window length - max freq char) <= K"),
(T1,M2,"Fixed window + freq map","Permutation in String","LeetCode","Medium","Does a fixed window match an anagram","Frequency map compared via a rolling window"),
(T1,M2,"Expand-then-shrink window","Minimum Window Substring","LeetCode","Hard","Smallest window containing all target chars","Expand right to satisfy, shrink left to minimize"),
(T1,M2,"Monotonic deque window","Sliding Window Maximum","LeetCode","Hard","Max value in every window of size k","Monotonic decreasing deque; front is always the answer"),
(T1,M2,"Variable window shrink","Minimum Size Subarray Sum","LeetCode","Medium","Shortest subarray with sum >= target","Expand right, shrink left while sum stays valid"),
(T1,M2,"At-most-K-distinct window","Fruit Into Baskets","LeetCode","Medium","Longest subarray with at most 2 distinct values","Window pattern: shrink whenever distinct count exceeds limit"),
(T1,M2,"Bounded-count window","Max Consecutive Ones III","LeetCode","Medium","Longest run allowing K zero-flips","Window stays valid while zero-count inside it <= K"),
]

DATA += [
(T2,M3,"Bracket matching stack","Valid Parentheses","LeetCode","Easy","Matching brackets","Stack pushes opens, pops and checks on every close"),
(T2,M3,"Auxiliary min stack","Min Stack","LeetCode","Medium","O(1) minimum retrieval","Auxiliary stack tracks the running minimum"),
(T2,M3,"Operand stack","Evaluate Reverse Polish Notation","LeetCode","Medium","Postfix expression evaluation","Stack of operands; pop two per operator seen"),
(T2,M3,"Bounded backtracking","Generate Parentheses","LeetCode","Medium","All valid bracket combinations","Backtrack with live open-count/close-count bounds"),
(T2,M3,"Monotonic decreasing stack","Daily Temperatures","LeetCode","Medium","Days until a warmer temperature","Monotonic decreasing stack of waiting indices"),
(T2,M3,"Stack simulation","Car Fleet","LeetCode","Medium","Count fleets reaching the destination","Sort by position, stack of arrival times"),
(T2,M3,"Monotonic stack width","Largest Rectangle in Histogram","LeetCode","Hard","Max rectangle area under a skyline","Monotonic stack tracks left boundary per bar height"),
(T2,M3,"Histogram row trick","Maximal Rectangle","LeetCode","Hard","Max all-1s rectangle in a binary matrix","Apply the histogram trick row by row, accumulating heights"),
(T2,M3,"Monotonic stack, circular","Next Greater Element I & II","LeetCode","Easy/Medium","Next bigger element to the right (possibly circular)","Monotonic stack; traverse array twice for the circular case"),
(T2,M3,"Greedy monotonic stack","Remove K Digits","LeetCode","Medium","Smallest number after removing K digits","Monotonic increasing stack, greedily pop larger digits"),
(T2,M3,"Signed operand stack","Basic Calculator II","LeetCode","Medium","Evaluate expression with + - * /","Stack holds signed operands, resolve precedence inline"),
(T2,M3,"Explosive stack simulation","Asteroid Collision","LeetCode","Medium","Simulate collisions between moving asteroids","Stack; pop while the top asteroid explodes on collision"),
(T2,M4,"Classic template","Binary Search (classic)","LeetCode","Easy","Find exact value in a sorted array","Standard lo/hi/mid template"),
(T2,M4,"Lower bound","Search Insert Position","LeetCode","Easy","Where would a value be inserted","Lower-bound binary search"),
(T2,M4,"Boundary search x2","Find First and Last Position of Element","LeetCode","Medium","Range of a target value","Two separate searches: leftmost bound, rightmost bound"),
(T2,M4,"Half-sorted detection","Search in Rotated Sorted Array","LeetCode","Medium","Search inside a rotated sorted array","Determine which half is sorted, narrow accordingly"),
(T2,M4,"Pivot detection","Find Minimum in Rotated Sorted Array","LeetCode","Medium","Find the rotation pivot","Compare mid to right boundary to locate pivot side"),
(T2,M4,"Flattened 1D search","Search a 2D Matrix","LeetCode","Medium","Search a fully sorted matrix","Treat the 2D grid as one flattened sorted array"),
(T2,M4,"Slope-following search","Find Peak Element","LeetCode","Medium","Local maximum, array need not be sorted","Binary search by walking toward the upward slope"),
(T2,M4,"Binary search on answer","Koko Eating Bananas","LeetCode","Medium","Minimize the maximum eating rate","Binary search over the answer space itself"),
(T2,M4,"Binary search on answer","Capacity To Ship Packages Within D Days","LeetCode","Medium","Minimize the max daily load","Binary search on answer + greedy feasibility check"),
(T2,M4,"Binary search on answer","Split Array Largest Sum","LeetCode","Hard","Minimize the largest partition sum","Same binary-search-on-answer + feasibility template"),
(T2,M4,"Binary search on partition","Median of Two Sorted Arrays","LeetCode","Hard","O(log(m+n)) median of two arrays","Binary search on the partition point, not the values"),
(T2,M4,"Binary search on stored pairs","Time Based Key-Value Store","LeetCode","Medium","Get value at or before a timestamp","Binary search over stored (timestamp, value) list per key"),
(T2,M4,"Binary search on answer","Aggressive Cows","GFG","Hard","Maximize the minimum distance between placements","Binary search on answer, greedy placement feasibility check"),
(T2,M4,"Binary search on answer","Allocate Minimum Number of Pages","GFG","Hard","Minimize the max pages assigned to any student","Binary search on answer, same feasibility template as Koko"),
(T2,M5,"Pointer reversal","Reverse Linked List","LeetCode","Easy","Reverse the pointers of a list","Iterative prev/curr/next pointer swap"),
(T2,M5,"Dummy head merge","Merge Two Sorted Lists","LeetCode","Easy","Merge two sorted chains","Dummy head node + compare-and-attach loop"),
(T2,M5,"Floyd's cycle detection","Linked List Cycle","LeetCode","Easy","Detect a loop in a list","Slow/fast pointer; they meet if a cycle exists"),
(T2,M5,"Floyd's + reset pointer","Linked List Cycle II","LeetCode","Medium","Find the cycle's starting node","After meeting, reset one pointer to head, move both by 1"),
(T2,M5,"Find-mid, reverse, merge","Reorder List","LeetCode","Medium","Interleave first and second half","Find middle, reverse second half, merge alternately"),
(T2,M5,"Fixed-gap two pointer","Remove Nth Node From End of List","LeetCode","Medium","One-pass removal from the end","Two pointers kept a fixed gap apart"),
(T2,M5,"Interweave then detach","Copy List with Random Pointer","LeetCode","Medium","Deep copy a list with an extra random pointer","Interweave copies into original list, then detach"),
(T2,M5,"Carry propagation","Add Two Numbers","LeetCode","Medium","Add numbers stored as linked lists","Carry propagates node by node during traversal"),
(T2,M5,"Doubly linked list + hashmap","LRU Cache","LeetCode","Medium","O(1) get/put with least-recently-used eviction","Doubly linked list ordered by recency + hashmap"),
(T2,M5,"Frequency-bucketed lists","LFU Cache","LeetCode","Hard","Evict the least frequently used entry","Hashmap of frequency buckets, each its own doubly linked list"),
(T2,M5,"Find-mid, reverse, compare","Palindrome Linked List","LeetCode","Easy","Check symmetry in O(1) extra space","Find middle, reverse second half, compare both halves"),
(T2,M5,"Two running tails","Odd Even Linked List","LeetCode","Medium","Regroup nodes by index parity","Maintain two running tails, splice them together at the end"),
(T2,M5,"DFS with explicit stack","Flatten a Multilevel Doubly Linked List","LeetCode","Medium","Flatten nested child sublists","DFS using an explicit stack, relinking as you go"),
(T2,M5,"K-way heap merge","Merge K Sorted Lists","LeetCode","Hard","Combine K sorted chains into one","Min-heap of (value, list_id), or divide and conquer"),
(T2,M6,"Merge on overlap","Insert Interval","LeetCode","Medium","Insert into a sorted, non-overlapping set","Merge with neighbors on overlap while scanning through"),
(T2,M6,"Sort + sequential merge","Merge Intervals","LeetCode","Medium","Collapse all overlapping intervals","Sort by start time, merge sequentially"),
(T2,M6,"Greedy end-time sort","Non-overlapping Intervals","LeetCode","Medium","Minimum removals for zero overlap","Sort by end time, greedily keep earliest-ending"),
(T2,M6,"Sort + adjacency check","Meeting Rooms","LeetCode","Easy","Can one person attend all meetings","Sort by start time, check adjacent pairs overlap"),
(T2,M6,"Min-heap of end times","Meeting Rooms II","LeetCode","Medium","Minimum rooms needed simultaneously","Min-heap of end times, or a start/end sweep line"),
(T2,M6,"Two pointer overlap","Interval List Intersections","LeetCode","Medium","Overlap between two sorted interval lists","Two pointer; overlap = max(starts) to min(ends)"),
(T2,M6,"Greedy end-time sort","Minimum Number of Arrows to Burst Balloons","LeetCode","Medium","Minimum points to cover all ranges","Sort by end coordinate, greedily place each arrow"),
(T2,M6,"Merge all + find gaps","Employee Free Time","LeetCode","Hard","Common gaps across many people's schedules","Merge every interval across all people, find the gaps"),
(T2,M6,"Overlap check structure","My Calendar I / II","LeetCode","Medium","Book an event without double/triple overlap","Brute overlap scan, or an interval-tree style structure"),
]

DATA += [
(T3,M7,"Recursive mirror","Invert Binary Tree","LeetCode","Easy","Mirror the tree","Swap left and right children recursively"),
(T3,M7,"Recursive height","Maximum Depth of Binary Tree","LeetCode","Easy","Height of the tree","1 + max(left depth, right depth)"),
(T3,M7,"Paired recursion","Same Tree","LeetCode","Easy","Structural and value equality","Recursive pairwise comparison of both trees"),
(T3,M7,"Same-tree at every node","Subtree of Another Tree","LeetCode","Easy","Does a tree contain this exact subtree","Run the Same-Tree check rooted at every node"),
(T3,M7,"Global max while returning height","Diameter of Binary Tree","LeetCode","Easy","Longest path, may not pass through root","Track a global max while the recursion returns height"),
(T3,M7,"Bottom-up short circuit","Balanced Binary Tree","LeetCode","Easy","Height-balanced check","Bottom-up height calc with an early -1 short circuit"),
(T3,M7,"BFS by level","Binary Tree Level Order Traversal","LeetCode","Medium","Process the tree level by level","BFS with a queue, track the size of each level"),
(T3,M7,"Level order + flip flag","Binary Tree Zigzag Level Order Traversal","LeetCode","Medium","Alternate direction per level","Level order traversal with an alternating flip flag"),
(T3,M7,"Last-of-level BFS","Binary Tree Right Side View","LeetCode","Medium","Last visible node per level","BFS, keep only the last node processed at each level"),
(T3,M7,"DFS carrying running max","Count Good Nodes in Binary Tree","LeetCode","Medium","Node value >= all its ancestors","DFS carrying the max value seen so far downward"),
(T3,M7,"Bounds-passing DFS","Validate Binary Search Tree","LeetCode","Medium","Valid BST check","DFS passing down a (low, high) valid-range bound"),
(T3,M7,"Inorder + counter","Kth Smallest Element in a BST","LeetCode","Medium","Kth value in sorted order","Inorder traversal, stop once count reaches K"),
(T3,M7,"BST ordering branch","Lowest Common Ancestor of a BST","LeetCode","Medium","LCA using BST's sorted property","Branch left or right purely from value comparison"),
(T3,M7,"Both-subtree DFS","Lowest Common Ancestor of a Binary Tree","LeetCode","Medium","LCA with no ordering guarantee","DFS; the node found in both branches is the LCA"),
(T3,M7,"Index-mapped reconstruction","Construct Binary Tree from Preorder and Inorder Traversal","LeetCode","Medium","Rebuild a tree from two traversal orders","Inorder splits left/right; hashmap gives O(n) lookup"),
(T3,M7,"Global var + return extension","Binary Tree Maximum Path Sum","LeetCode","Hard","Best path, which can bend at a node","Global variable for the answer; return only the straight extension"),
(T3,M7,"Null-marker preorder","Serialize and Deserialize Binary Tree","LeetCode","Hard","Convert tree to string and back","Preorder DFS with explicit null markers"),
(T3,M8,"Backtracking on path list","Path Sum II","LeetCode","Medium","All root-to-leaf paths summing to target","Backtrack, adding and removing nodes on the current path"),
(T3,M8,"Prefix-sum-on-tree","Path Sum III","LeetCode","Medium","Any-node-to-any-descendant path sum","Prefix sum idea applied to a tree, using a hashmap"),
(T3,M8,"Tuple state tree DP","House Robber III","LeetCode","Medium","Max sum with no adjacent parent-child","Each node returns a (rob, skip) tuple upward"),
(T3,M8,"Three-state greedy-DP","Binary Tree Cameras","LeetCode","Hard","Minimum cameras to cover every node","Three-state greedy-DP evaluated bottom-up from leaves"),
(T3,M8,"Excess accumulation DFS","Distribute Coins in Binary Tree","LeetCode","Medium","Minimum moves to balance coins across nodes","DFS returns excess coins; accumulate abs(excess) globally"),
(T3,M8,"Rerooting DP","Sum of Distances in Tree","LeetCode","Hard","Distance sum computed from every node","Rerooting technique gives an O(n) answer, not O(n^2)"),
(T3,M8,"Careful leaf-aware DFS/BFS","Minimum Depth of Binary Tree","LeetCode","Easy","Shortest path to a leaf","BFS or careful DFS - note the leaf definition matters here"),
(T3,M8,"In-place right-skew rewire","Flatten Binary Tree to Linked List","LeetCode","Medium","Collapse the tree into a right-skewed list","Reverse-postorder rewiring, done in place"),
(T3,M8,"O(1) space level linking","Populating Next Right Pointers in Each Node","LeetCode","Medium","Connect nodes on the same level","Use the already-built next pointers, no extra queue needed"),
(T3,M8,"Coordinate BFS + tie-break sort","Vertical Order Traversal of a Binary Tree","LeetCode","Hard","Group node values by column","BFS with (row, col) coordinates, sort ties by value"),
(T3,M8,"Left-edge + leaves + right-edge","Boundary Traversal of Binary Tree","GFG","Medium","Print only the boundary of the tree","Left boundary, then leaves, then right boundary in reverse"),
(T3,M8,"Two-longest-branch generalization","Diameter of N-ary Tree","LeetCode","Medium","Longest path in a general (non-binary) tree","Same two-longest-branches idea, generalized to N children"),
(T3,M9,"Nested-node trie","Implement Trie (Prefix Tree)","LeetCode","Medium","Insert / search / startsWith on strings","Nested dict or array-of-26 children per node"),
(T3,M9,"Trie + wildcard DFS","Design Add and Search Words Data Structure","LeetCode","Medium","Search supporting a wildcard '.' character","DFS through all children whenever a wildcard is hit"),
(T3,M9,"Trie + pruned board DFS","Word Search II","LeetCode","Hard","Find many words on a single board","Build the trie once, DFS board with prefix-based pruning"),
(T3,M9,"Trie early termination","Replace Words","LeetCode","Medium","Replace a word with its shortest dictionary root","Trie search that stops at the first complete root found"),
(T3,M9,"Trie + prefix-check DFS","Longest Word in Dictionary","LeetCode","Medium","Longest word buildable one letter at a time","Trie plus DFS/BFS checking 'isWord' at every prefix"),
(T3,M9,"Binary trie over bits","Maximum XOR of Two Numbers in an Array","LeetCode","Medium","Maximize pairwise XOR of array elements","Binary trie over bits, greedily walk the opposite bit"),
]

DATA += [
(T4,M10,"Min-heap of size K","Kth Largest Element in an Array","LeetCode","Medium","Kth largest value, unsorted input","Min-heap of size K, or quickselect partitioning"),
(T4,M10,"Fixed-size min-heap","Kth Largest Element in a Stream","LeetCode","Easy","Maintain the kth largest as values stream in","Fixed-size min-heap, push and pop as new values arrive"),
(T4,M10,"Max-heap simulation","Last Stone Weight","LeetCode","Easy","Repeatedly smash the two heaviest stones","Max-heap simulation of pairwise smashing"),
(T4,M10,"Max-heap of size K","K Closest Points to Origin","LeetCode","Medium","K nearest points by distance","Max-heap of size K, evict the farthest as needed"),
(T4,M10,"Max-heap + cooldown queue","Task Scheduler","LeetCode","Medium","Minimum time to run tasks with a cooldown","Max-heap by frequency, paired with a cooldown queue"),
(T4,M10,"Per-user heap merge","Design Twitter","LeetCode","Medium","Merge K feeds ordered by recency","Heap-merge of most-recent tweets across followees"),
(T4,M10,"Two balanced heaps","Find Median from Data Stream","LeetCode","Hard","Running median of a live stream","Max-heap for the low half, min-heap for the high half"),
(T4,M10,"Two coordinated heaps","IPO (Maximize Capital)","LeetCode","Hard","Pick projects to maximize final capital","Two heaps: affordable-by-capital, then best-by-profit"),
(T4,M10,"Max-heap alternation","Reorganize String","LeetCode","Medium","No two adjacent characters may match","Max-heap by frequency, alternate placement of top two"),
(T4,M10,"Heap-based merge sequence","Ugly Number II","LeetCode","Medium","Nth number with only factors 2, 3, 5","Min-heap or three-pointer merge across the three factor lines"),
(T4,M10,"K-way heap merge","Merge K Sorted Arrays","GFG","Medium","Combine K sorted arrays into one","Heap holds (value, array_id, index) tuples"),
(T4,M10,"Heap + global max tracking","Smallest Range Covering Elements from K Lists","LeetCode","Hard","Smallest range touching all K lists at once","Heap advance plus a tracked global maximum"),
(T4,M10,"Bottom-up sift-down","Heapify (Build a Heap from an Array)","GFG","Medium","Convert an array into a heap in O(n)","Bottom-up sift-down, not repeated top-down insertion"),
(T4,M11,"Include/exclude tree","Subsets","LeetCode","Medium","All subsets of a set","Include/exclude recursion tree over each element"),
(T4,M11,"Sort + skip-at-depth","Subsets II","LeetCode","Medium","All subsets with duplicate elements present","Sort first, skip a repeated value at the same recursion depth"),
(T4,M11,"Swap-based or used-array","Permutations","LeetCode","Medium","All orderings of a set","Swap-based backtracking or a used[] tracking array"),
(T4,M11,"Sort + skip-at-depth","Permutations II","LeetCode","Medium","All orderings with duplicate elements present","Sort, then skip a repeated value at the same recursion depth"),
(T4,M11,"Reuse via fixed index","Combination Sum","LeetCode","Medium","Unlimited reuse, sum to a target","Recurse without advancing the index, allowing reuse"),
(T4,M11,"No reuse + dedupe","Combination Sum II","LeetCode","Medium","No reuse, duplicates present in input","Sort, skip same value at same depth, always advance index"),
(T4,M11,"Bounded count + sum prune","Combination Sum III","LeetCode","Medium","Exactly K numbers summing to N","Bounded backtracking pruned by remaining count and sum"),
(T4,M11,"DFS + visited backtrack","Word Search","LeetCode","Medium","Path spelling a word on a letter grid","DFS with visited marking, then backtrack to unmark"),
(T4,M11,"Backtrack + palindrome check","Palindrome Partitioning","LeetCode","Medium","All partitions where every part is a palindrome","Backtrack over cut points, checking palindrome per part"),
(T4,M11,"Position-indexed backtrack","Letter Combinations of a Phone Number","LeetCode","Medium","Digit-to-letter mapping combinations","Backtrack over each digit position in sequence"),
(T4,M11,"Conflict-set backtrack","N-Queens","LeetCode","Hard","Place N queens with no attacks","Backtrack tracking column and both diagonal conflict sets"),
(T4,M11,"Constraint-checked backtrack","Sudoku Solver","LeetCode","Hard","Fill a valid Sudoku board","Backtrack with row/column/box constraint checks per cell"),
(T4,M11,"Length + range pruning","Restore IP Addresses","LeetCode","Medium","Insert dots to form a valid IP address","Backtrack pruned by remaining length and 0-255 value range"),
(T4,M11,"Grid DFS + visited","Rat in a Maze","GFG","Medium","Find a path from start to end in a grid","Backtrack with a visited grid, unmark on the way back"),
(T4,M12,"Farthest-reach tracking","Jump Game","LeetCode","Medium","Can you reach the last index","Greedy tracking of the farthest index reachable so far"),
(T4,M12,"Level-expansion greedy","Jump Game II","LeetCode","Medium","Minimum jumps to reach the end","Greedy expansion resembling BFS levels, one jump at a time"),
(T4,M12,"Deficit tracking","Gas Station","LeetCode","Medium","Circular feasibility of a route","If total gas >= total cost, exactly one start point works"),
(T4,M12,"Sorted greedy run-building","Hand of Straights","LeetCode","Medium","Group cards into consecutive runs","Sorted count map, greedily build each run from its smallest card"),
(T4,M12,"Filter + coordinate covering","Merge Triplets to Form Target Triplet","LeetCode","Medium","Combine triplets via element-wise max","Filter valid triplets, confirm every target coordinate is covered"),
(T4,M12,"Last-occurrence greedy","Partition Labels","LeetCode","Medium","Split so no letter spans two parts","Greedy split using each letter's last-occurrence index"),
(T4,M12,"Feasible-range tracking","Valid Parenthesis String","LeetCode","Medium","'*' can act as ( or ) or nothing","Track the feasible [low, high] range of open-bracket count"),
(T4,M12,"Cost-difference sort","Two City Scheduling","LeetCode","Medium","Assign people to cities minimizing total cost","Sort by the cost difference between the two cities"),
(T4,M12,"Two pointer greedy match","Assign Cookies","LeetCode","Easy","Match greedy needs to sizes, both sorted","Two pointer greedy matching between sorted arrays"),
(T4,M12,"Two-pass greedy","Candy","LeetCode","Hard","Min candies, higher rating beats each neighbor","Two passes: left-to-right, then right-to-left, taking the max"),
(T4,M12,"Sweep with two pointers","Minimum Number of Platforms","GFG","Medium","Overlapping arrival/departure events","Sort both arrival and departure arrays, sweep with two pointers"),
(T4,M12,"Sort by end time","Activity Selection","GFG","Easy","Maximum non-overlapping activities","Sort by end time, greedily pick the next compatible activity"),
]

DATA += [
(T5,M13,"Flood fill DFS/BFS","Number of Islands","LeetCode","Medium","Count connected regions of land","DFS/BFS flood fill, marking visited cells as you go"),
(T5,M13,"Flood fill + area count","Max Area of Island","LeetCode","Medium","Size of the largest connected land region","Flood fill that returns the area of each region visited"),
(T5,M13,"Hashmap old-to-new DFS/BFS","Clone Graph","LeetCode","Medium","Deep copy an entire graph","DFS/BFS with a hashmap mapping old node to new node"),
(T5,M13,"Multi-source BFS","Walls and Gates (Islands and Treasure)","LeetCode","Medium","Distance from every cell to nearest gate","Multi-source BFS starting from all gates simultaneously"),
(T5,M13,"Multi-source BFS by level","Rotting Oranges","LeetCode","Medium","Minimum time for spread to reach everywhere","Multi-source BFS, tracking elapsed time by level"),
(T5,M13,"Reverse BFS from both borders","Pacific Atlantic Water Flow","LeetCode","Medium","Cells that can reach both oceans","Reverse BFS inward from both borders, then intersect results"),
(T5,M13,"Border-first DFS","Surrounded Regions","LeetCode","Medium","Flip only fully enclosed regions","DFS from the border first to mark safe (unflippable) cells"),
(T5,M13,"Cycle detection, directed","Course Schedule","LeetCode","Medium","Can all courses be finished given prerequisites","Cycle detection in a directed graph, via DFS or Kahn's"),
(T5,M13,"Topological sort output","Course Schedule II","LeetCode","Medium","Output one valid course order","Topological sort, Kahn's BFS or reversed DFS post-order"),
(T5,M13,"Union-Find cycle check","Graph Valid Tree","LeetCode","Medium","n nodes, n-1 edges, connected and acyclic","Union-Find; a failed union anywhere means a cycle exists"),
(T5,M13,"Union-Find or DFS count","Number of Connected Components in an Undirected Graph","LeetCode","Medium","Count disjoint groups in a graph","Union-Find, or DFS launched from every unvisited node"),
(T5,M13,"Union-Find, first failure","Redundant Connection","LeetCode","Medium","Find the one edge creating a cycle","Union-Find; the first edge that fails to union is the answer"),
(T5,M13,"BFS on implicit word graph","Word Ladder","LeetCode","Hard","Min transformations, one letter changed at a time","BFS over an implicit graph of one-letter-different words"),
(T5,M13,"BFS levels + DFS reconstruct","Word Ladder II","LeetCode","Hard","All shortest transformation sequences","BFS to build levels, then DFS backward to reconstruct paths"),
(T5,M13,"BFS on board positions","Snakes and Ladders","LeetCode","Medium","Minimum dice rolls to reach the end","BFS on board positions, using boustrophedon index mapping"),
(T5,M13,"8-directional BFS","Shortest Path in Binary Matrix","LeetCode","Medium","Shortest path allowing 8-directional moves","Plain BFS, expanding to all 8 neighboring cells"),
(T5,M13,"Multi-source BFS","As Far from Land as Possible","LeetCode","Medium","Water cell maximizing distance from any land","Multi-source BFS starting from every land cell at once"),
(T5,M14,"Union-Find keyed by string","Accounts Merge","LeetCode","Medium","Merge accounts that share any email","Union-Find where the key is the email string itself"),
(T5,M14,"Weighted Union-Find or DFS","Evaluate Division","LeetCode","Medium","a/b given a set of known ratios","Weighted Union-Find, or DFS multiplying ratios along the path"),
(T5,M14,"Graph build + topo sort","Alien Dictionary","LeetCode","Hard","Derive letter order from a sorted word list","Build a graph from adjacent-word comparisons, topological sort"),
(T5,M14,"Greedy + max-heap swap","Course Schedule III","LeetCode","Hard","Max courses schedulable before their deadlines","Greedy plus a max-heap to swap out the worst-fit course"),
(T5,M14,"Leaf-peeling BFS","Minimum Height Trees","LeetCode","Medium","Find the tree's center node(s)","Repeatedly peel away leaves in BFS layers"),
(T5,M14,"Two-color BFS/DFS","Is Graph Bipartite?","LeetCode","Medium","Is the graph 2-colorable","BFS/DFS coloring; any conflict means it's not bipartite"),
(T5,M14,"Bipartite via coloring","Possible Bipartition","LeetCode","Medium","Split people into two mutually-disliking groups","Model dislikes as edges, run the bipartite coloring check"),
(T5,M14,"Union-Find + post-check","Satisfiability of Equality Equations","LeetCode","Medium","'==' and '!=' constraints must be consistent","Union-Find over equalities first, verify inequalities after"),
(T5,M15,"Dijkstra from source","Network Delay Time","LeetCode","Medium","Time for a signal to reach every node","Standard Dijkstra run once from the source node"),
(T5,M15,"Bellman-Ford, bounded rounds","Cheapest Flights Within K Stops","LeetCode","Medium","Shortest path under a hop-count limit","Bellman-Ford limited to exactly K relaxation rounds"),
(T5,M15,"Dijkstra, maximize product","Path with Maximum Probability","LeetCode","Medium","Path maximizing a product of edge weights","Dijkstra variant that maximizes instead of minimizes"),
(T5,M15,"Dijkstra on max-so-far","Swim in Rising Water","LeetCode","Hard","Minimize the max cell value along a path","Priority queue on max-so-far, or binary search plus BFS"),
(T5,M15,"MST via Prim or Kruskal","Min Cost to Connect All Points","LeetCode","Medium","MST over points using Manhattan distance","Prim's (heap-grow) or Kruskal's (sorted edges + Union-Find)"),
(T5,M15,"MST via Kruskal","Connecting Cities With Minimum Cost","LeetCode","Medium","MST over an explicit list of weighted edges","Kruskal's algorithm using Union-Find"),
(T5,M15,"MST with virtual node","Optimize Water Distribution in a Village","LeetCode","Hard","MST combining wells and connecting pipes","MST using a virtual source node representing all wells"),
(T5,M15,"Tarjan's low-link DFS","Critical Connections in a Network","LeetCode","Hard","Find every bridge edge in a graph","Tarjan's algorithm using low-link values during DFS"),
(T5,M15,"Union-Find or DFS count","Number of Provinces","LeetCode","Medium","Count connected groups from an adjacency matrix","Union-Find, or DFS launched from every unvisited city"),
(T5,M15,"Hierholzer's algorithm","Reconstruct Itinerary","LeetCode","Hard","Eulerian path, lexicographically smallest","Hierholzer's algorithm walking a sorted adjacency structure"),
(T5,M15,"Floyd-Warshall","Find the City With the Smallest Number of Neighbors at a Threshold Distance","LeetCode","Medium","All-pairs shortest path under a distance cap","Floyd-Warshall, then count reachable cities per node"),
(T5,M15,"Bellman-Ford cycle check","Detect Negative Cycle in a Graph","GFG","Hard","Does a negative-weight cycle exist","Bellman-Ford; if an edge still relaxes after V-1 rounds, cycle exists"),
]

DATA += [
(T6,M16,"Fibonacci-shaped recurrence","Climbing Stairs","LeetCode","Easy","Count ways to climb, 1 or 2 steps at a time","dp[i] = dp[i-1] + dp[i-2]"),
(T6,M16,"Adjacent-exclusion DP","House Robber","LeetCode","Medium","Max sum with no two adjacent picks","dp[i] = max(dp[i-1], dp[i-2] + nums[i])"),
(T6,M16,"Two linear DP passes","House Robber II","LeetCode","Medium","Same problem, but the array is circular","Run the linear version twice: excluding first, then excluding last"),
(T6,M16,"Split-based counting DP","Decode Ways","LeetCode","Medium","Count ways to decode a digit string","dp based on valid 1-digit and 2-digit splits at each position"),
(T6,M16,"Unbounded knapsack, min","Coin Change","LeetCode","Medium","Minimum coins to make an amount","Unbounded knapsack, dp indexed over amount"),
(T6,M16,"Unbounded knapsack, count","Coin Change II","LeetCode","Medium","Count the ways to make an amount","Unbounded knapsack; looping coins outer makes it combinations"),
(T6,M16,"Track running max and min","Maximum Product Subarray","LeetCode","Medium","Product subarray, sign can flip","Track running max AND running min simultaneously"),
(T6,M16,"Dict-lookup DP","Word Break","LeetCode","Medium","Can a string be segmented using a dictionary","dp[i] true if some dp[j] true and s[j:i] is in the dictionary"),
(T6,M16,"O(n^2) or patience-sort DP","Longest Increasing Subsequence","LeetCode","Medium","Length of the longest increasing subsequence","O(n^2) DP, or O(n log n) patience sorting with binary search"),
(T6,M16,"0/1 knapsack, target half","Partition Equal Subset Sum","LeetCode","Medium","Split array into two equal-sum halves","0/1 knapsack with target = total_sum / 2"),
(T6,M16,"Knapsack reframing","Target Sum","LeetCode","Medium","Assign +/- signs to hit a target","Reframe as counting a subset summing to (total+target)/2"),
(T6,M16,"Unbounded knapsack style DP","Perfect Squares","LeetCode","Medium","Min square numbers summing to n","Unbounded-knapsack-style dp over the target value n"),
(T6,M16,"Include/exclude 2D DP","0/1 Knapsack","GFG","Medium","Max value under a weight capacity","dp[i][w]: include-or-exclude decision at each item"),
(T6,M16,"Unbounded knapsack, ordered count","Combination Sum IV","LeetCode","Medium","Count ordered ways to reach a target","Unbounded dp; looping amount outer makes it permutations"),
(T6,M17,"Grid path counting DP","Unique Paths","LeetCode","Medium","Count paths across a grid","dp[i][j] = dp[i-1][j] + dp[i][j-1]"),
(T6,M17,"Grid DP with blocked cells","Unique Paths II","LeetCode","Medium","Grid path counting with obstacles","Same recurrence, but zero out any blocked cell"),
(T6,M17,"Grid min-cost DP","Minimum Path Sum","LeetCode","Medium","Minimum-cost path across a grid","dp[i][j] = cell value + min(up, left)"),
(T6,M17,"2D match/skip DP","Longest Common Subsequence","LeetCode","Medium","Length of a shared subsequence","2D dp with a match-vs-skip-one recurrence"),
(T6,M17,"Expand-around-center or 2D table","Longest Palindromic Substring","LeetCode","Medium","Longest substring that is a palindrome","Expand-around-center for every index, or a 2D dp table"),
(T6,M17,"Expand-around-center count","Palindromic Substrings","LeetCode","Medium","Count all palindromic substrings","Expand-around-center from every position, count each hit"),
(T6,M17,"2D ops-count DP","Edit Distance","LeetCode","Hard","Min operations to transform string A into B","2D dp over insert/delete/replace transitions"),
(T6,M17,"2D consumed-prefix DP","Interleaving String","LeetCode","Medium","Can two strings interleave to form a third","2D dp tracking how much of each source string is consumed"),
(T6,M17,"2D match/skip counting","Distinct Subsequences","LeetCode","Hard","Count ways t appears as a subsequence of s","2D dp with a match-or-skip counting recurrence"),
(T6,M17,"Corner-based square DP","Maximal Square","LeetCode","Medium","Largest all-1s square in a binary matrix","dp[i][j] = min(up, left, diagonal) + 1 when the cell is 1"),
(T6,M17,"2D DP with wildcard transitions","Regular Expression Matching","LeetCode","Hard","Pattern matching with '.' and '*'","2D dp with a special transition rule for the '*' operator"),
(T6,M17,"2D DP with wildcard transitions","Wildcard Matching","LeetCode","Hard","Pattern matching with '?' and '*'","2D dp; '*' can match empty or absorb one extra character"),
(T6,M17,"State-machine DP","Best Time to Buy and Sell Stock with Cooldown","LeetCode","Medium","Trading with a mandatory cooldown day","3-state dp: holding, just-sold, resting"),
(T6,M17,"Transaction-indexed DP","Best Time to Buy and Sell Stock III","LeetCode","Hard","Max profit with at most 2 transactions","dp indexed by transaction count and current hold-state"),
(T6,M18,"Bottom-up, space-optimized DP","Triangle","LeetCode","Medium","Min path sum from top to bottom","Bottom-up dp, space-optimized down to a single 1D row"),
(T6,M18,"Precompute + 1D cut DP","Palindrome Partitioning II","LeetCode","Hard","Min cuts so every part is a palindrome","Precompute a palindrome table, then a 1D min-cuts dp"),
(T6,M18,"Interval DP, choose last","Burst Balloons","LeetCode","Hard","Max coins from bursting balloons in some order","Interval dp; choose the LAST balloon burst in each range"),
(T6,M18,"Interval DP, character merge","Strange Printer","LeetCode","Hard","Minimum printer turns to produce a string","Interval dp built on a character-merging insight"),
(T6,M18,"Catalan-number DP","Unique Binary Search Trees","LeetCode","Medium","Count structurally unique BSTs on n nodes","Catalan-number recurrence over the count of nodes"),
(T6,M18,"Root-choice recursive construction","Unique Binary Search Trees II","LeetCode","Medium","Generate every structurally unique BST","Recursive construction choosing each possible root in turn"),
(T6,M18,"DFS + memoization on grid","Longest Increasing Path in a Matrix","LeetCode","Hard","Longest strictly increasing path in a grid","DFS with memoization; no explicit visited array is needed"),
(T6,M18,"Backtracking + bitmask memo","Partition to K Equal Sum Subsets","LeetCode","Medium","Split an array into K equal-sum groups","Backtracking combined with bitmask memoization"),
(T6,M18,"Bitmask BFS","Shortest Path Visiting All Nodes","LeetCode","Hard","TSP-style shortest walk visiting every node","Bitmask BFS; state = (current node, visited-mask)"),
(T6,M18,"Bitmask DP, TSP","Traveling Salesman Problem","GFG","Hard","Min-cost tour visiting every city once","Bitmask dp; state = (current city, visited-mask)"),
(T6,M18,"Bitmask DP over assignments","Minimum XOR Sum of Two Arrays","LeetCode","Medium","Pair elements across arrays to minimize XOR sum","Bitmask dp iterating over which elements are assigned"),
(T6,M18,"Interval DP, same framing trick","Minimum Cost to Cut a Stick","LeetCode","Hard","Min cost to make all given cuts on a stick","Interval dp choosing cut order; same 'frame last, not first' trick as Burst Balloons"),
(T6,M18,"Topological order + relax once","Longest Path in a Directed Acyclic Graph","GFG","Medium","Longest path in a graph with no cycles","Topological order, relax each edge exactly once - no Dijkstra needed"),
(T6,M18,"Dijkstra + path-count DP","Number of Ways to Arrive at Destination","LeetCode","Medium","Count shortest paths in a weighted graph","Dijkstra combined with a path-counting dp layered on top"),
]

DATA += [
(T7,M19,"XOR cancellation","Single Number","LeetCode","Easy","Everyone appears twice except one","XOR of everything cancels every pair, leaving the answer"),
(T7,M19,"Bit-count mod 3","Single Number II","LeetCode","Medium","Everyone appears three times except one","Track bit counts mod 3 across all numbers"),
(T7,M19,"XOR + split by set bit","Single Number III","LeetCode","Medium","Two unique numbers hidden among pairs","XOR all values, then split the group by their lowest set bit"),
(T7,M19,"Bit-clearing trick","Number of 1 Bits","LeetCode","Easy","Count set bits (popcount)","n & (n-1) clears the lowest set bit; repeat and count"),
(T7,M19,"DP on prior popcount","Counting Bits","LeetCode","Easy","Popcount for every value from 0 to n","dp[i] = dp[i >> 1] + (i & 1)"),
(T7,M19,"Bit-by-bit shift and OR","Reverse Bits","LeetCode","Easy","Reverse a 32-bit integer's bits","Shift and OR one bit at a time into the result"),
(T7,M19,"XOR or sum-formula trick","Missing Number","LeetCode","Easy","Find the missing number in 0..n","XOR trick, or the closed-form sum formula"),
(T7,M19,"Bitwise sum simulation","Sum of Two Integers","LeetCode","Medium","Add two numbers without + or -","XOR gives the sum bits, AND-then-shift gives the carry, loop"),
(T7,M19,"Common-prefix shrink","Bitwise AND of Numbers Range","LeetCode","Medium","AND of every number in a range","Right-shift both bounds together to find their common prefix"),
(T7,M19,"Bitmask enumeration","Subsets via Bitmask","GFG","Medium","Generate every subset of a set","Iterate 0..2^n - 1; bit i set means element i is included"),
(T7,M19,"Bitmask enumeration","Power Set (bitmask variant)","GFG","Medium","All subsets, viewed through a bit-trick lens","Same bitmask enumeration, reframed for the counting mindset"),
(T7,M19,"XOR self-inverse formula","Gray Code","LeetCode","Medium","Sequence where consecutive values differ by 1 bit","Closed-form formula: i XOR (i >> 1)"),
(T7,M20,"KMP failure function","Implement strStr() (KMP)","LeetCode","Easy","Substring search","KMP failure function avoids re-scanning a matched prefix"),
(T7,M20,"KMP failure/LPS array","Longest Happy Prefix","LeetCode","Hard","Longest prefix that is also a suffix","The KMP failure (LPS) array directly gives the answer"),
(T7,M20,"KMP or rolling hash","Repeated String Match","LeetCode","Medium","Min repeats of A so B becomes a substring","KMP, or a rolling hash, applied to the concatenation"),
(T7,M20,"Mirror-symmetry expansion","Longest Palindromic Substring (Manacher's technique)","LeetCode","Medium","O(n) longest palindromic substring","Manacher's algorithm expands using mirror symmetry"),
(T7,M20,"KMP on augmented string","Shortest Palindrome","LeetCode","Hard","Min characters to prepend for a palindrome","KMP applied to s + separator + reverse(s)"),
(T7,M20,"Substring-of-doubled-string trick","Rotate String","LeetCode","Easy","Is one string a rotation of another","Check if the target is a substring of s concatenated with itself"),
(T7,M20,"Rolling hash search","Rabin-Karp Substring Search","GFG","Medium","Pattern search using hashing","Rolling hash comparison, O(1) hash update per shift"),
(T7,M20,"Z-array construction","Z-Function Pattern Matching","GFG","Hard","Find pattern occurrences via a Z-array","Z-array gives longest common prefix with the whole string, per index"),
(T7,M20,"Vertical scan or trie","Longest Common Prefix","LeetCode","Easy","Shared prefix across a list of strings","Vertical character-by-character scanning, or a shared trie"),
(T7,M20,"Stack-based nested build","Decode String","LeetCode","Medium","Nested k[encoded] pattern to expand","Stack holds (previous_string, repeat_count); build inside-out"),
(T7,M21,"Euclidean algorithm","GCD / LCM Computation","GFG","Easy","Greatest common divisor of two numbers","gcd(a, b) = gcd(b, a mod b), recursively"),
(T7,M21,"Mark multiples from p^2","Sieve of Eratosthenes","GFG","Medium","All primes up to N","Mark multiples of each prime starting from p squared"),
(T7,M21,"Sieve-based counting","Count Primes","LeetCode","Medium","Count primes strictly below n","Sieve-based marking, then count the unmarked entries"),
(T7,M21,"Square-and-multiply","Modular Exponentiation","GFG","Medium","Compute a^b mod m efficiently","Fast exponentiation via repeated squaring and multiplying"),
(T7,M21,"Bit trick or log check","Power of Two / Three / Four","LeetCode","Easy","Check if n is a power of a given base","Bit trick n & (n-1) == 0 for base 2, or a log-based check"),
(T7,M21,"Positional base-26 value","Excel Sheet Column Number","LeetCode","Easy","Convert a column label to its number","Positional value logic, same idea as any base conversion"),
(T7,M21,"Divide and conquer squaring","Pow(x, n)","LeetCode","Medium","Fast exponentiation for real numbers","Divide-and-conquer squaring, careful handling of negative n"),
(T7,M21,"Binary search on the answer","Sqrt(x)","LeetCode","Easy","Integer square root of x","Binary search over the candidate answer range"),
(T7,M21,"Parity pattern recognition","Nim Game","LeetCode","Easy","Game theory: last player to move wins","Losing position exactly when stones % 4 == 0"),
(T7,M21,"Interval DP or parity insight","Stone Game","LeetCode","Medium","Optimal alternating picks from a row of piles","Interval dp on the subarray, or a math parity shortcut"),
(T7,M21,"Parity pattern recognition","Divisor Game","LeetCode","Easy","Win or lose determined by parity","Pattern recognition: an even starting n always wins"),
(T7,M21,"Closed-form vs DP comparison","Unique Paths via Combinatorics (nCr)","GFG","Medium","Count grid paths using a formula","Closed-form C(m+n-2, m-1), compared against the dp approach"),
(T7,M22,"Static prefix sum","Range Sum Query - Immutable","LeetCode","Easy","Static range sum queries","Prefix sum array, O(1) per query"),
(T7,M22,"Binary Indexed Tree","Range Sum Query - Mutable","LeetCode","Medium","Range sum queries with point updates","Binary Indexed Tree (Fenwick Tree)"),
(T7,M22,"2D prefix sum","Range Sum Query 2D - Immutable","LeetCode","Medium","Static 2D range sum queries","2D prefix sum, O(1) per query after O(nm) build"),
(T7,M22,"BIT over compressed values","Count of Smaller Numbers After Self","LeetCode","Hard","Inversion-style counting per element","BIT over compressed values, or a merge-sort-based count"),
(T7,M22,"Segment tree, min merge","Range Minimum Query (Segment Tree)","GFG","Hard","Range min queries with point updates","Segment tree where the merge operation is min(left, right)"),
(T7,M22,"Segment tree, sum merge","Build Segment Tree for Range Sum","GFG","Hard","Range sum queries with point updates","Segment tree where the merge operation is left + right"),
(T7,M22,"Segment tree + lazy tags","Lazy Propagation for Range Update","GFG","Hard","Range update plus range query, both efficient","Segment tree with lazy tags, deferring pushes until needed"),
(T7,M22,"Block-based precomputation","Sqrt Decomposition for Range Sum","Codeforces/CP","Medium","Block-based range query technique","Precompute block sums, giving O(sqrt n) per query"),
(T7,M22,"Sparse table, power-of-2 ranges","Sparse Table for Range Minimum","GFG","Hard","Static range min, O(1) per query","Sparse table precomputing answers over power-of-2-length ranges"),
(T7,M22,"BIT over rank buckets","Design a Leaderboard","LeetCode","Medium","Dynamic kth order statistic","BIT over score/rank buckets to answer order-statistic queries"),
]

print(f"TOTAL: {len(DATA)}")
